#+TITLE: GNU Emacs Config
#+AUTHOR: Nilesh Jawarkar
#+DESCRIPTION: Config
#+STARTUP: showeverything
#+OPTIONS: toc:2

* Table of contents :toc:
- [[#basic-setup][Basic setup]]
- [[#install-package-manager][Install Package Manager]]
- [[#manage-package-updates][Manage package updates]]
- [[#theme][Theme]]
- [[#evil-mode][Evil mode]]
- [[#org-mode-configuration][Org mode configuration]]
  - [[#use-default-org-when-using-org-file-to-configure-emacs][Use default org, when using org file to configure emacs]]
  - [[#indent-config][Indent config]]
  - [[#enable-bullests-replace-][Enable bullests, replace *]]
  - [[#enable-toc][Enable TOC]]
- [[#general-key-bindings][General key-bindings]]
- [[#which-key-configuration][Which-key configuration]]

* Basic setup

#+begin_src emacs-lisp
;; Do not show the startup screen
(setq inhibit-startup-message t)

;; Disable tool bar, menu bar, scroll bar.
(tool-bar-mode -1)
(menu-bar-mode -1)
(scroll-bar-mode -1)
(toggle-scroll-bar -1)

;; Some other settings
(blink-cursor-mode -1)
(global-hl-line-mode +1)
(line-number-mode +1)
(global-display-line-numbers-mode +1)
(column-number-mode t)
(size-indication-mode t)

(prefer-coding-system 'utf-8)
(set-default-coding-systems 'utf-8)
(set-terminal-coding-system 'utf-8)
(set-keyboard-coding-system 'utf-8)
#+end_src

* Install Package Manager

#+begin_src emacs-lisp
(defvar bootstrap-version)
(let ((bootstrap-file
       (expand-file-name "straight/repos/straight.el/bootstrap.el" user-emacs-directory))
      (bootstrap-version 6))
  (unless (file-exists-p bootstrap-file)
    (with-current-buffer
        (url-retrieve-synchronously
         "https://raw.githubusercontent.com/radian-software/straight.el/develop/install.el"
         'silent 'inhibit-cookies)
      (goto-char (point-max))
      (eval-print-last-sexp)))
  (load bootstrap-file nil 'nomessage))

(straight-use-package 'use-package)
#+end_src

* Manage package updates

#+begin_src emacs-lisp
(use-package auto-compile
    :straight t
    :config (auto-compile-on-load-mode))
(setq load-prefer-newer t)
#+end_src

* Theme

#+begin_src emacs-lisp
(set-face-attribute 'default nil :font "SauceCodePro Nerd Font" :height 120)
;;(set-face-attribute 'default nil :font "Mononoki Nerd Font" :height 130)
(add-to-list 'default-frame-alist '(font . "SauceCodePro Nerd Font"))
(add-to-list 'default-frame-alist '(height . 35))
(add-to-list 'default-frame-alist '(width . 135))
(setq-default line-spacing 0.12)

(use-package nerd-icons
    :straight t)

(use-package doom-themes
    :straight t
    :ensure t
    :config
    (load-theme 'doom-one t)
    (doom-themes-visual-bell-config))

(use-package doom-modeline
    :straight t
    :ensure t
    :init (doom-modeline-mode 1))
#+end_src

* Evil mode

#+begin_src emacs-lisp
(use-package evil
    :straight t
    :init      ;; tweak evil's configuration before loading it
    (setq evil-want-integration t) ;; This is optional since it's already set to t by default.
    (setq evil-want-keybinding nil)
    (setq evil-vsplit-window-right t)
    (setq evil-split-window-below t)
    (evil-mode))
(use-package evil-collection
    :straight t
    :after evil
    :config
    (setq evil-collection-mode-list '(dashboard dired ibuffer))
    (evil-collection-init))
#+end_src

* Org mode configuration

** Use default org, when using org file to configure emacs

If using org file for configuring emacs, please use default org mode implementation.
This is because, installing new org version with straight, will lead to *conflict* with 
default org implementation. Its due to default org implementation will get loaded even
before running babel to convert config.org to config.el. And this config.el is resposible for installing new org
implementation and configure it.

** Indent config

#+begin_src emacs-lisp
(add-hook 'org-mode-hook 'org-indent-mode)
;; Org mode source blocks have some really weird and annoying default indentation behavior, disable it.
(electric-indent-mode -1)
#+end_src

** Enable bullests, replace *

#+begin_src emacs-lisp
(use-package org-bullets
  :straight t)
(add-hook 'org-mode-hook (lambda () (org-bullets-mode 1)))
(setq org-hide-leading-stars t)
#+end_src

** Enable TOC
#+begin_src emacs-lisp
(use-package toc-org
    :straight t
    :commands toc-org-enable
    :init (add-hook 'org-mode-hook 'toc-org-enable))
#+end_src

* General key-bindings

#+begin_src emacs-lisp
(use-package general
  :straight t
  :config
  (general-evil-setup)

  ;; set up space as the global leader key
  (general-create-definer nj/leader-keys
  :states '(normal insert visual emacs)
  :keymaps 'override
  :prefix "SPC"
  :global-prefix "M-SPC")

  (nj/leader-keys
  "b" '(:ignore t :wk "buffer")
  "bb" '(switch-to-buffer :wk "Switch buffer")
  "bk" '(kill-this-buffer :wk "Kill this buffer")
  "bn" '(next-buffer :wk "Next buffer")
  "bp" '(previous-buffer :wk "Previous buffer")
  "br" '(revert-buffer :wk "Reload buffer"))
)
#+end_src

* Which-key configuration

#+begin_src emacs-lisp
(use-package which-key
    :straight t
    :init
    (which-key-mode 1)
    :config
    (setq which-key-side-window-location 'bottom
    which-key-sort-order #'which-key-key-order-alpha
    which-key-sort-uppercase-first nil
    which-key-add-column-padding 1
    which-key-max-display-columns nil
    which-key-min-display-lines 6
    which-key-side-window-slot -10
    which-key-side-window-max-height 0.25
    which-key-idle-delay 0.8
    which-key-max-description-length 25
    which-key-allow-imprecise-window-fit t
    which-key-separator " -> " ))
#+end_src
